### ISSUE TITLE
goalign detecting amino acid file as nucleotide file

### ISSUE THREAD

**Issue by frikinzi** [evolbioinfo/goalign#14]
Thank you for developing this helpful tool. 

I'm running into an issue with goalign compute where the tool is automatically detecting my file as a nucleotide file even though there are amino acid characters in it (S, Y, T). Below I include a snippet of my .faa file. 

```
>GCA_0
SCYTGAK
>GCA_1
SAYSASK
>GCA_2
SAYSASK
>GCA_3
SAYSASK
```

The command I ran is: goalign compute pssm -i N85.faa > N85.count.tsv

The output of that command is this, when I would expect there to be amino acid characters.
<img width="262" alt="Screenshot 2023-11-13 at 4 44 55 PM" src="https://github.com/evolbioinfo/goalign/assets/86448602/cde477a1-2bfe-4eb9-9a38-ba0b3452a2ba">

I tried including --auto-detect, but it didn't fix my problem.

I installed goalign through conda.

Any help would be appreciated. Please let me know if I can provide any other information. Thank you!

**Comment by fredericlemoine** [comment]
Hi,
Thank you for your suggestion. 
I've been thinking of adding this feature for a while. I've just added the option "--alphabet" to goalign commands. If you have a way to test it, it would be great.
Thanks

**Comment by frikinzi** [comment]
I just tested it and it worked! Thanks so much for the quick response and fix.
