### ISSUE TITLE
Add support for Stockholm files

### ISSUE THREAD

**Issue by apcamargo** [evolbioinfo/goalign#15]
Stockholm is a widely-used format for protein and nucleotide MSAs (largely due to its adoption by Pfam and Rfam). MSAs retrieved from InterPro are also provided in this format.

It would be handy if `goalign` supported the Stockholm files.

**Comment by fredericlemoine** [comment]
Hi,
Thank you for the suggestion.
I've made an initial attempt at parsing the Stockholm format, which can be accessed using the `-k` option.
If you try it out, feel free to let me know if you encounter any issues.

**Comment by apcamargo** [comment]
Somewhat related to this issue, it would be useful if the `reformat` command supported conversion to Stockholm. Right now `goalign` can only read Stockholm, but not convert other formats to it.

**Comment by fredericlemoine** [comment]
Thank you for the comment, it was an omission, the functions were already implemented.

**Comment by apcamargo** [comment]
Thank you, @fredericlemoine! Do you have plans to make a new release soon?
