### ISSUE TITLE
How does this compare to EASEL ?

### ISSUE THREAD

**Issue by tseemann** [evolbioinfo/goalign#4]
I was looking for advice on how EASEL and goalign compare?

https://github.com/EddyRivasLab/easel

**Comment by fredericlemoine** [comment]
There is obviously an intersection in terms of functionalities. However goalign was originally developed to provide a simple and cross platform command line utility to handle sequences and alignments in a phylogenetic perspective (bootstrap, distance matrices with several models, etc.). It goes with [gotree](https://github.com/evolbioinfo/gotree), which handles phylogenetic trees. As it is developed in go, it also provides an api usable in go programs.
Tell me if you need more information,
Best

**Comment by tseemann** [comment]
Ok thank you for the clarification.
