### ISSUE TITLE
Remove list of columns and column ranges

### ISSUE THREAD

**Issue by tseemann** [evolbioinfo/goalign#7]
If i have a text file of positions  i want to remove from an alignment.
Like `subseq` but i can choose all positions (or inverse)

```
% cat seq.afa
>x
-ATGC
>y
TATG-
>z
ATCGG

% cat pos.txt
1
3
5

% goalign subseq --sitefile post.txt < seq.afa
>x
AG
>y
AG
>z
TG
```

Also would like option for the `pos.txt` to be relative to a specified "reference" taxon which ignores it's gaps.

**Comment by fredericlemoine** [comment]
Dear Torsten, 

Thanks for your suggestion.

1) If you want a sub-sequence relative to a reference sequence you can do it with `goalign subseq --ref-seq <sequence name>`. However, it will not take all coordinates from a file.

2) If you want to select several columns from an alignment, a workaround would be to use the `goalign split --partition` command, which takes all columns defined in the partition file and output them in a separate file. That way you can define several partitions. However this one does not take reference coordinates without gaps yet...
Example of a partition file:
```
M1,p1=1-12/3,2-12/3
M2,p2=3-12/3
```
It will output 2 files: 
1) `p1.fa`: with first and second nucleotides of each codon from position 1 to 12 (1-based)
2) `p2.fa`: with third nucleotide each codon from position 1 to 12 (1-based)

3) So I implemented the command `goalign subsites`, which extracts given sites from an input alignment. Options `--ref-seq`, `--reverse` and `--sitefile`are implemented.

Do not hesitate to tell me if it is what you were looking for.

**Comment by tseemann** [comment]
@fredericlemoine thanks for the quick response!
1. I tried this but then realised it only supported 1 range (same as esl-alimask)
2. i saw that, but could not find documentation on the partition file (it's cool, but clunky for this)
3. that is awesome! it's in the dev branch i see. i really need tagged releases to deploy.

**Comment by fredericlemoine** [comment]
I just "pre"-released [v0.3.3c](https://github.com/evolbioinfo/goalign/releases/tag/v0.3.3c)

**Comment by tseemann** [comment]
Thanks! Just installed now and testing.

**Comment by fredericlemoine** [comment]
Hi @tseemann ,
Can I close this issue?
Also, If you want to have a look, I implemented the [extract](https://github.com/evolbioinfo/goalign/blob/master/docs/commands/extract.md) command, to extract several sub-alignments from an input alignment.
