### ISSUE TITLE
Add options to allow partial bootstrap sampling.

### ISSUE THREAD

**Issue by xiekunwhy** [evolbioinfo/goalign#8]
Hi,

Can you add some options to allow users to do partial bootstrap sampling, say that the total length of my sequence is 10Mb, but I just want 1Mb when do bootsraping using goalign build seqboot/distboot.

Best,
Kun

**Comment by fredericlemoine** [comment]
Hi Kun, 

I am not sure that resampling with replacement 1Mb over 10Mb will give statistically robust supports. 
Maybe a simple [subsampling](https://en.wikipedia.org/wiki/Resampling_(statistics)#Subsampling) can solve your problem? (I just added this option: `goalign sample sites --consecutive=false` on the [v0.3.3d release](https://github.com/evolbioinfo/goalign/releases/tag/v0.3.3d).
Let me know what you think.

Best,
Frederic

**Comment by xiekunwhy** [comment]
Hi Frederic,

I just want an alternative tool to realize Jackknife function in phylip-seqboot, not exactly sub-resampling with replacement, jackknife is useful when computation resources and time is limited, and it can avoid some potential problems of bootstrap.

Do you have any plan to add some options or functions to do jackknifle or parametric bootstrap?

Best,
Kun

**Comment by fredericlemoine** [comment]
Hi,

If you think it is useful, you can try to use the option `--frac/-f` of `build seqboot/distboot` just implemented in this [pre-release](https://github.com/evolbioinfo/goalign/releases/tag/v0.3.3e).
If this answers your question, feel free to close the issue,

Best,
Frédéric

**Comment by xiekunwhy** [comment]
Hi,

Thank you very much, and I am now close it.

Best,
Kun
