### ISSUE TITLE
goalign tranpose

### ISSUE THREAD

**Issue by tseemann** [evolbioinfo/goalign#9]
I am not sure if this can be done with existing comamnd:

```
% cat in.afa
>seq1
AAAA
>seq2
CCTT
>seq3
ACGT

% goalign transpose < in.afa 

>1
ACA
>2
ACC
>3
ATG
>4
ATT

% goalgn transpose -v 

# go from transposed back to alignment
```

**Comment by fredericlemoine** [comment]
I added `goalign transpose` command (see [doc](https://github.com/evolbioinfo/goalign/blob/master/docs/commands/transpose.md)), available in this [pre-release](https://github.com/evolbioinfo/goalign/releases/tag/v0.3.3f).
Let me know if it helps.
